name: Docker Build and Deploy

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub (optional, if you want to push to Docker Hub)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t darwin.simbajon-dg/vite-react-app:latest .

      # Step 4: Push the Docker image to Docker Hub (optional)
      - name: Push Docker image
        run: docker push darwin.simbajon-dg/vite-react-app:latest

      # Step 5: Run the container (optional, for testing)
      - name: Run Docker container
        run: docker run -d -p 5173:5173 darwin.simbajon-dg/vite-react-app:latest
