on:
  workflow_run:
    workflows:
      - Build Workflow  # Name of the first workflow
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository }}/chabcav-web-app:latest
    env:
      SVC_ID: chabcav-web-app
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:     
      - uses: actions/checkout@v3
      - run: |
          # Download the script
          curl -fsSL https://railway.app/install.sh -o install.sh
          # Debug: Check the content of the script
          cat install.sh
          # Install tar if not present
          if ! command -v tar &> /dev/null; then
            sudo apt-get update && sudo apt-get install -y tar
          fi
          # Run the installation script
          sh install.sh
          # Add Railway to PATH
          echo 'export PATH="$HOME/.railway/bin:$PATH"' >> $GITHUB_ENV
        shell: bash
      - run: railway up --service=${{ env.SVC_ID }}
