on:
  workflow_run:
    workflows:
      - Build Workflow  # Name of the first workflow
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository }}/chabcav-web-app:latest
    env:
      SVC_ID: chabcav-web-app
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:     
       # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Railway CLI
      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

       # Step 3: Deploy to Railway
      - name: Install Railway CLI
        run: railway up --service=${{ env.SVC_ID }}
