on:
  workflow_run:
    workflows:
      - Build Workflow  # Name of the first workflow
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository }}/chabcav-web-app:latest
    env:
      SVC_ID: chabcav-web-app
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:     
       # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Railway CLI
      - name: Install Railway CLI
        shell: sh
        run: |
          curl -Lo railway https://github.com/railwayapp/cli/releases/latest/download/railway-linux-amd64
          chmod +x railway
          sudo mv railway /usr/local/bin/
        env:
          PATH: $PATH:$HOME/.local/bin

       # Step 3: Deploy to Railway
      - name: Deploy to Railway 
        run: railway up --service=${{ env.SVC_ID }}
