name: Deploy to Railway

on:
  push:
    branches:
      - develop  # Adjust to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REPO_ACTOR }}
          password: ${{ secrets.REPO_TOKEN }}

      # Step 3: Build and push the Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest -f chabcav-web/Dockerfile.dev .
          docker push ghcr.io/${{ github.repository }}:latest
       
      # Step 2: Trigger Railway Deployment
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          curl -X POST "https://backboard.railway.app/graphql/v2" \
            -H "Authorization: Bearer $RAILWAY_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "query": "mutation Deploy($image: String!) { createDeployment(input: { projectId: \"3c8c5294-0f7f-458f-82f0-532df1c89143\", image: $image }) { deployment { id status } } }",
              "variables": {
                "image": "ghcr.io/darwin.simbajon-dg/chabcav-web:latest"
              }
            }'
