name: Development - Deploy to Railway

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.REPO_ACTOR }}
        password: ${{ secrets.REPO_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ghcr.io/darwin-simbajon-dg/chabcav-web:latest
        file: chabcav-web/Dockerfile.dev
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    container: ghcr.io/darwin-simbajon-dg/chabcav-web:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Railway CLI
      run: |
        curl -sSL https://railway.app/install.sh | sh

    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: railway up --service chabcav-web
      

  
