name: Deploy to Railway

on:
  push:
    branches:
      - develop  # Adjust to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REPO_ACTOR }}
          password: ${{ secrets.REPO_TOKEN }}

      # Step 3: Build and push the Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest -f Dockerfile.dev .
          docker push ghcr.io/${{ github.repository }}:latest
       
      - name: Install Railway CLI
        run: |
          curl -sSL https://railway.app/install.sh | sh

      - name: Set Railway Token
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: echo "Railway token set"

      # Step 4: Deploy the image to Railway
      - name: Deploy to Railway
        run: |
          railway up --image ghcr.io/${{ github.repository }}:latest
