name: Development - Deploy to Railway

on:
  push:
    branches:
      - develop

jobs:
    
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Railway CLI
      run: |
        curl -sSL https://github.com/railwayapp/cli/releases/latest/download/railway-linux-amd64.tar.gz -o railway.tar.gz
        tar -xzf railway.tar.gz -C /usr/local/bin
        chmod +x /usr/local/bin/railway

    - name: Authenticate Railway CLI
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        echo $RAILWAY_TOKEN > ~/.railway
        echo "Authentication completed"

    - name: Link Railway Project
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: railway link --project 3c8c5294-0f7f-458f-82f0-532df1c89143 --service d2a7195a-cf7b-4d2d-af38-625d25b54934

    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: railway up --detach

    
      

  
