name: Development - Deploy to Railway

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.REPO_ACTOR }}
        password: ${{ secrets.REPO_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ghcr.io/darwin-simbajon-dg/chabcav-web:latest
        file: chabcav-web/Dockerfile.dev
  
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: my-service
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
    - run: echo "Railway token set"
    - run: railway link --project 3c8c5294-0f7f-458f-82f0-532df1c89143 --service d2a7195a-cf7b-4d2d-af38-625d25b54934
    - run: railway up --service=d2a7195a-cf7b-4d2d-af38-625d25b54934 --image gchr.io/darwin-simbajon-dg/chabcav-web:latest
      

  
