name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Heroku Container Registry
      run: |
        echo "$DOCKER_PASSWORD" | docker login --username=dps0421 --password-stdin registry.heroku.com

    - name: Build Docker image
      run: docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/chabcav-web-app ./chabcav-web

    - name: Push Docker image to Heroku
      run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/chabcav-web-app

    - name: Release Heroku app
      run: |
        heroku container:release chabcav-web-app --app ${{ secrets.HEROKU_APP_NAME }}
