name: Deploy to Railway

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the main branch
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Railway CLI
      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo 'export PATH="$HOME/.railway/$PATH"' >> $GITHUB_ENV

       # Step 3: Link Railway Project
      - name: Link Railway Project
        env:
          RAILWAY_API_TOKEN: 4d8a19bf-d6f2-4ec6-a287-7973951a1bc4
        run: railway link --project=3c8c5294-0f7f-458f-82f0-532df1c89143

      # Step 4: Deploy to Railway
      - name: Deploy to Railway
        env:
          RAILWAY_API_TOKEN: 4d8a19bf-d6f2-4ec6-a287-7973951a1bc4
        run: railway up
