name: Deploy to Railway

on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/chabcav-web-app:latest ./chabcav-web

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GT_TOKEN }}" | docker login ghcr.io -u darwin-simbajon-dg --password-stdin

      # Step 4: Push Docker image to GHCR
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/chabcav-web-app:latest
        
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository }}/chabcav-web-app:latest
    env:
      SVC_ID: chabcav-web-app
      RAILWAY_TOKEN: 4d8a19bf-d6f2-4ec6-a287-7973951a1bc4
    steps:
      - uses: actions/checkout@v3
      - run: railway up --service=chabcav-web-app
