name: Deploy to Railway

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the main branch
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Railway CLI
      - name: Set up Railway
        uses: railwayapp/cli-action@v2
        with:
          token: ${{ secrets.RAILWAY_API_TOKEN }}

      # Step 3: Deploy to Railway
      - name: Deploy to Railway
        run: railway up
