name: Deploy to Railway

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the main branch
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub (optional if you want to push to Docker Hub)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: dps0421
          password: $p1derS0421

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t chabcav-web-app ./chabcav-web

      # Step 4: Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push dps0421/chabcav-web-app:latest

       # Step 4: Push Docker image to Railway
      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo 'export PATH="$HOME/.railway/bin:$PATH"' >> $GITHUB_ENV

      # Step 6: Deploy to Railway
      - name: Deploy to Railway
        env:
          RAILWAY_API_TOKEN: 4d8a19bf-d6f2-4ec6-a287-7973951a1bc4
        run: railway up --service=chabcav-web
