name: Deploy to Railway

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the main branch
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Railway CLI
      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo 'export PATH="$HOME/.railway/bin:$PATH"' >> $GITHUB_ENV
          source $GITHUB_ENV

      # Step 3: Deploy to Railway using API token
      - name: Deploy to Railway
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: railway up 
