name: Deploy React App to Railway

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Railway's container registry
      - name: Log in to Railway's container registry
        env:
          RAILWAY_API_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $RAILWAY_API_TOKEN | docker login --username=dps0421 --password-stdin registry.railway.app

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t registry.railway.app/chabcav-web/chabcav-web-app ./chabcav-web

      # Step 4: Push Docker image to Railway's container registry
      - name: Push Docker image
        run: docker push registry.railway.app/chabcav-web/chabcav-web-app

      # Step 5: Trigger Deployment
      - name: Trigger Deployment
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: |
          curl -X POST -H "Authorization: Bearer $RAILWAY_API_TOKEN" \
               -H "Content-Type: application/json" \
               -d '{"serviceId": "<service-id>"}' \
               https://backboard.railway.app/graphql
